### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-romania#13]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] l10n_ro_account_bank_statement_import_mt940_brd in #23 
- [x] l10n_ro_config in #17 
- [x] l10n_ro_partner_create_by_vat in #14 
- [x] l10n_ro_partner_unique in #15 
- [x] l10n_ro_siruta in #16 
- [x] l10n_ro_vat_on_payment in #25

**Comment by feketemihai** [comment]
@OCA/local-romania-maintainers @OCA/core-maintainers  I saw lately some localisations that merged certain PR's without any other reviews, it is ok this situation, how i can get all the PR's merged, since there are no reviews, there are a lot of PR's ready to be merged, Ci tools green, with tests more than 90%. I know that most of the @OCA/core-maintainers are busy with own projects, and don't have time to review localisation projects, since they are in front of different laws, procedures...can i merge alone this PR's, without any other review?

**Comment by pedrobaeza** [comment]
It depends on the localization involvement. In this case, as you are the only contributor in this project, I think it's OK that you merge PRs while they are green.

**Comment by feketemihai** [comment]
@pedrobaeza Thanks for info and quick reaction.
