### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-romania#324]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate
- [x] currency_rate_update_RO_BNR - By @vasi26ro - #659
- [x] l10n_ro_account @dhongu #639
- [x] l10n_ro_account_anaf_sync @dhongu #563
- [x] l10n_ro_account_bank_statement_import_mt940_alpha @dhongu #640
- [x] l10n_ro_account_bank_statement_import_mt940_base @dhongu #638
- [x] l10n_ro_account_bank_statement_import_mt940_bcr @dhongu #641
- [x] l10n_ro_account_bank_statement_import_mt940_brd @dhongu #642
- [x] l10n_ro_account_bank_statement_import_mt940_ing @dhongu #643
- [x] l10n_ro_account_bank_statement_import_mt940_rffsn @dhongu #644
- [x] l10n_ro_account_bank_statement_report by @stananatanaela in #527
- [x] l10n_ro_account_edi_ubl @dhongu #564
- [x] l10n_ro_account_edit_currency_rate by @stananatanaela in #512 
- [x] l10n_ro_account_period_close #645
- [x] l10n_ro_account_report_invoice by @stananatanaela in #505 
- [ ] l10n_ro_address_extended
- [x] l10n_ro_city by @dhongu in #521 
- [x] l10n_ro_config by @stananatanaela in #502 
- [x] l10n_ro_dvi @dhongu #675
- [x] l10n_ro_fiscal_validation by @feketemihai in #524 
- [x] l10n_ro_nondeductible_vat @feketemihai in #919 
- [x] l10n_ro_partner_create_by_vat by @feketemihai in #504 
- [x] l10n_ro_partner_unique by @feketemihai in #503 
- [x] l10n_ro_payment_receipt_report @dhongu #637
- [x] l10n_ro_payment_to_statement by @danila12 #635
- [ ] l10n_ro_siruta
- [x] l10n_ro_stock by @feketemihai in #522 
- [x] l10n_ro_stock_account by @feketemihai in #523 
- [X] l10n_ro_stock_account_date by @feketemihai in #525 
- [X] l10n_ro_stock_account_date_wizard by @feketemihai in #526 
- [x] l10n_ro_stock_account_mrp by @feketemihai in #922
- [x] l10n_ro_stock_account_notice by @adrian-dks  @dhongu #565
- [x] l10n_ro_stock_picking_comment_template by @feketemihai in #923 
- [x] l10n_ro_stock_account_reception_in_progress
- [x] l10n_ro_stock_picking_valued_report by @feketemihai in #920 
- [x] l10n_ro_stock_price_difference by @adrian-dks @dhongu #566
- [x] l10n_ro_stock_report by @dhongu #562
- [x] l10n_ro_vat_on_payment by @feketemihai in #510 

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
